require("lze").load({
	----{
	----	"indent-blankline.nvim",
	----	for_cat = "general.extra",
	----	event = "DeferredUIEnter",
	----	after = function(plugin)
	----		require("ibl").setup()
	----	end,
	----},
	-- {
	--   "hlargs",
	--   for_cat = 'general.extra',
	--   event = "DeferredUIEnter",
	--   -- keys = "",
	--   dep_of = { "nvim-lspconfig" },
	--   after = function(plugin)
	--     require('hlargs').setup {
	--       color = '#32a88f',
	--     }
	--     vim.cmd([[hi clear @lsp.type.parameter]])
	--     vim.cmd([[hi link @lsp.type.parameter Hlargs]])
	--   end,
	-- },
})
